#FROM python:3.6.6-alpine
#FROM python:3-slim
FROM python:3.9-slim-buster
WORKDIR /app
ADD . .
#RUN apk update
RUN apt-get update
RUN pip3 install -r requirements.txt
EXPOSE 5000
ENTRYPOINT ["python3"]
CMD ["twtr.py"]